/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import dominio.Cita;
import dominio.Historia;
import dominio.Paciente;
import java.util.List;
import org.json.JSONObject;
import servicio.HistoriaService;

/**
 *
 * @author Lenovo
 */
public class DialogVerHistoria extends javax.swing.JDialog {

    List<Historia> historias;
    private HistoriaService service = new HistoriaService();
    /**
     * Creates new form DialogVerHistoria
     */
    public DialogVerHistoria(java.awt.Frame parent, boolean modal,Paciente paciente) {
        super(parent, modal);
        initComponents();
        historias = service.encontrarHistoriaPaciente(paciente);
        this.setLocationRelativeTo(null);
        llenarDatos();
    }
    
    public void llenarDatos(){
        Historia h = historias.get(0);
        JSONObject estado = new JSONObject(h.getEstadoPaciente());
        String edad,peso,estatura,temperatura,pulso,disasolica,sistolica;
        String fechaCita,medico,motivo,diagnostico;
        edad = estado.getString("edad");
        peso = estado.getString("peso");
        estatura = estado.getString("estatura");
        temperatura = estado.getString("temperatura");
        pulso = estado.getString("pulso");
        disasolica = estado.getString("disasolica");
        sistolica = estado.getString("sistolica");
        JSONObject cita = new JSONObject(h.getCita());
        medico = cita.getString("doctor");
        fechaCita = cita.getString("fecha");
        motivo = cita.getString("motivo");
        diagnostico = h.getDiagnostico();
        txtNombrePaciente.setText(h.getPaciente().getFullName());
        txtNumDocumento.setText(h.getPaciente().getNumeroDocumento());
        txtEdad.setText(edad);
        txtPeso.setText(peso);
        txtPulso.setText(pulso);
        txtDisasolica.setText(disasolica);
        txtSisolica.setText(sistolica);txtEstatura.setText(estatura);
        txtTemperatura.setText(temperatura);
        txtFechacita.setText(fechaCita);
        txtMedico.setText(medico);
        areaMotivo.setText(motivo);
        jTextArea1.setText(diagnostico);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTemperatura = new jtextfieldround.JTextFieldRound();
        txtNombrePaciente = new jtextfieldround.JTextFieldRound();
        txtNumDocumento = new jtextfieldround.JTextFieldRound();
        txtEdad = new jtextfieldround.JTextFieldRound();
        txtFechacita = new jtextfieldround.JTextFieldRound();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMedico = new jtextfieldround.JTextFieldRound();
        txtPeso = new jtextfieldround.JTextFieldRound();
        txtEstatura = new jtextfieldround.JTextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDisasolica = new jtextfieldround.JTextFieldRound();
        txtPulso = new jtextfieldround.JTextFieldRound();
        txtSisolica = new jtextfieldround.JTextFieldRound();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMotivo = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIA CLINICA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 530, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Paciente :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 25));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Nro Documento : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 25));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Edad :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 25));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Fecha cita :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 25));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Medico :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 25));

        txtTemperatura.setFocusable(false);
        txtTemperatura.setRequestFocusEnabled(false);
        jPanel1.add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 100, 25));

        txtNombrePaciente.setFocusable(false);
        txtNombrePaciente.setRequestFocusEnabled(false);
        jPanel1.add(txtNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, 25));

        txtNumDocumento.setFocusable(false);
        txtNumDocumento.setRequestFocusEnabled(false);
        jPanel1.add(txtNumDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 180, 25));

        txtEdad.setFocusable(false);
        txtEdad.setRequestFocusEnabled(false);
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, 25));

        txtFechacita.setFocusable(false);
        txtFechacita.setRequestFocusEnabled(false);
        jPanel1.add(txtFechacita, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, 25));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 555, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Pulso: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 25));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Disasolica :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 25));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Sistolica:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 25));

        txtMedico.setFocusable(false);
        txtMedico.setRequestFocusEnabled(false);
        jPanel1.add(txtMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 25));

        txtPeso.setFocusable(false);
        txtPeso.setRequestFocusEnabled(false);
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, 25));

        txtEstatura.setFocusable(false);
        txtEstatura.setRequestFocusEnabled(false);
        jPanel1.add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, 25));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Peso: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 25));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Estatura :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 25));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Temperatura:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, 25));

        txtDisasolica.setFocusable(false);
        txtDisasolica.setRequestFocusEnabled(false);
        jPanel1.add(txtDisasolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 100, 25));

        txtPulso.setFocusable(false);
        txtPulso.setRequestFocusEnabled(false);
        jPanel1.add(txtPulso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 25));

        txtSisolica.setFocusable(false);
        txtSisolica.setRequestFocusEnabled(false);
        jPanel1.add(txtSisolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 100, 25));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("Motivo de consulta :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        areaMotivo.setColumns(20);
        areaMotivo.setLineWrap(true);
        areaMotivo.setRows(5);
        areaMotivo.setFocusable(false);
        areaMotivo.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(areaMotivo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 540, 60));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("Diagnostico :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 540, 180));

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 120, 35));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("IMPRIMIR");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 120, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogVerHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogVerHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogVerHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogVerHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogVerHistoria dialog = new DialogVerHistoria(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMotivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private jtextfieldround.JTextFieldRound txtDisasolica;
    private jtextfieldround.JTextFieldRound txtEdad;
    private jtextfieldround.JTextFieldRound txtEstatura;
    private jtextfieldround.JTextFieldRound txtFechacita;
    private jtextfieldround.JTextFieldRound txtMedico;
    private jtextfieldround.JTextFieldRound txtNombrePaciente;
    private jtextfieldround.JTextFieldRound txtNumDocumento;
    private jtextfieldround.JTextFieldRound txtPeso;
    private jtextfieldround.JTextFieldRound txtPulso;
    private jtextfieldround.JTextFieldRound txtSisolica;
    private jtextfieldround.JTextFieldRound txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
