package vista;

import dominio.Cita;
import dominio.Paciente;
import dominio.Persona;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import servicio.PacienteService;
import static util.FuncionesForm.*;

/**
 *
 * @author Lenovo
 */
public class DialogModificarPaciente extends javax.swing.JDialog {

    PacienteService pacienteService = new PacienteService();
    private String uriImg = null;
    
    public DialogModificarPaciente(java.awt.Frame parent, boolean modal, Paciente paciente) {
        super(parent, modal);
        initComponents();
        llenarDatos(paciente);
    }

    private void llenarDatos(Paciente paciente) {
        if (paciente.getFotoPerfil() != null) {
            lblImgUser.setIcon(cargarImagen(paciente, lblImgUser));
        }
        txtDocumento.setText(paciente.getNumeroDocumento());
        txtPrimerNombre.setText(paciente.getPrimerNombre());
        txtSegundoNombre.setText(paciente.getSegundoNombre());
        txtPrimerApellido.setText(paciente.getPrimerApellido());
        txtSegundoApellido.setText(paciente.getSegundoApellido());
        LocalDate date = paciente.getFechaNacimiento().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        calcularFecha(dcFechaNacimiento, date);
        cbSexo.setSelectedItem(paciente.getSexo());
        cbEps.setSelectedItem(paciente.getEps());
        txtEmail.setText(paciente.getEmail());
        txtCelular.setText(paciente.getCelular());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGuardarPaciente = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        cbSexo = new javax.swing.JComboBox<>();
        cbEps = new javax.swing.JComboBox<>();
        lblImgUser = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtDocumento = new jtextfieldround.JTextFieldRound();
        txtCelular = new jtextfieldround.JTextFieldRound();
        txtPrimerNombre = new jtextfieldround.JTextFieldRound();
        txtSegundoNombre = new jtextfieldround.JTextFieldRound();
        txtPrimerApellido = new jtextfieldround.JTextFieldRound();
        txtSegundoApellido = new jtextfieldround.JTextFieldRound();
        txtEmail = new jtextfieldround.JTextFieldRound();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelGuardarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        panelGuardarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        panelGuardarPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Primer Nombre*");
        panelGuardarPaciente.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 220, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Documento de identidad*");
        panelGuardarPaciente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel27.setText("Segundo Nombre");
        panelGuardarPaciente.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 220, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel28.setText("Primer Apellido*");
        panelGuardarPaciente.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 220, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel34.setText("Eps*");
        panelGuardarPaciente.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 120, -1));

        jLabel64.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel64.setText("Segundo Apellido*");
        panelGuardarPaciente.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 220, -1));

        jLabel65.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel65.setText("Fecha de Nacimiento*");
        panelGuardarPaciente.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 220, -1));

        jLabel66.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel66.setText("Sexo*");
        panelGuardarPaciente.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 60, -1));

        jLabel67.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel67.setText("Email*");
        panelGuardarPaciente.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 220, -1));

        jLabel68.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel68.setText("Celular*");
        panelGuardarPaciente.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 220, -1));

        jLabel78.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel78.setText("Fecha de Nacimiento*");
        panelGuardarPaciente.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 220, -1));

        dcFechaNacimiento.setBackground(new java.awt.Color(0, 0, 0, 0));
        panelGuardarPaciente.add(dcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 230, 30));

        cbSexo.setBackground(new java.awt.Color(0, 0, 0, 0));
        cbSexo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        panelGuardarPaciente.add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 70, 25));

        cbEps.setBackground(new java.awt.Color(0, 0, 0, 0));
        cbEps.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbEps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coosalud", "Sanistas", "Comfamiliar", "Nueva Eps" }));
        panelGuardarPaciente.add(cbEps, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 130, 25));

        lblImgUser.setBackground(new java.awt.Color(232, 230, 229));
        lblImgUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        panelGuardarPaciente.add(lblImgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, 150));

        jButton2.setBackground(new java.awt.Color(10, 92, 184));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Subir foto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelGuardarPaciente.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, -1));

        txtDocumento.setFocusable(false);
        txtDocumento.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtDocumento.setRequestFocusEnabled(false);
        panelGuardarPaciente.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, 30));

        txtCelular.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panelGuardarPaciente.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 230, 30));

        txtPrimerNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panelGuardarPaciente.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 230, 30));

        txtSegundoNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panelGuardarPaciente.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 230, 30));

        txtPrimerApellido.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panelGuardarPaciente.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 230, 30));

        txtSegundoApellido.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panelGuardarPaciente.add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 230, 30));

        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panelGuardarPaciente.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 230, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelGuardarPaciente.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 120, 40));

        jButton3.setBackground(new java.awt.Color(10, 92, 184));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Actualizar");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelGuardarPaciente.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelGuardarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelGuardarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        uriImg = escogerImagen(lblImgUser, this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Persona person = new Paciente();
        Paciente paciente;
        if(getDataForm(txtDocumento, txtPrimerNombre, txtSegundoNombre,
                txtPrimerApellido, txtSegundoApellido, txtEmail, txtCelular,
                dcFechaNacimiento, cbSexo, cbEps, uriImg, person)){
                paciente = (Paciente) person;
        }else {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos");
            return;
        }
        if (uriImg == null) {
            paciente.setFotoPerfil(null);
        }
        pacienteService.actualizarPaciente(paciente);
        JOptionPane.showMessageDialog(this, "Paciente Actualizado");
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numeroDocumento = txtDocumento.getText();
        Paciente paciente = pacienteService.encontrarPaciente(numeroDocumento);
        int respuesta = JOptionPane.showConfirmDialog(this, "Confirmar eliminacion. \nPaciente : "
                + paciente.getPrimerNombre() + " " + paciente.getPrimerApellido());
        if (respuesta == JOptionPane.YES_OPTION) {
//            Cita cita = new CitaDAO().existCitaPaciente(paciente);
//            if (cita != null) {
//                int r = JOptionPane.showConfirmDialog(this, "El paciente tiene citas agendadas desea continuar?");
//                if (r == JOptionPane.YES_OPTION) {
//                    new CitaDAO().eliminarCita(cita);
//                } else {
//                    return;
//                }
//            }
            pacienteService.eliminarPaciente(paciente);
            JOptionPane.showMessageDialog(this, "Paciente Eliminado");
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModificarPaciente dialog = new DialogModificarPaciente(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEps;
    private javax.swing.JComboBox<String> cbSexo;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblImgUser;
    private javax.swing.JPanel panelGuardarPaciente;
    private jtextfieldround.JTextFieldRound txtCelular;
    private jtextfieldround.JTextFieldRound txtDocumento;
    private jtextfieldround.JTextFieldRound txtEmail;
    private jtextfieldround.JTextFieldRound txtPrimerApellido;
    private jtextfieldround.JTextFieldRound txtPrimerNombre;
    private jtextfieldround.JTextFieldRound txtSegundoApellido;
    private jtextfieldround.JTextFieldRound txtSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
