package vista;

import dominio.Persona;
import static util.FuncionesForm.*;
import dominio.Recepcionista;
import java.awt.Color;
import javax.swing.JOptionPane;
import servicio.RecepcionistaService;

public class DialogModificarRecepcionista extends javax.swing.JDialog {

    private RecepcionistaService recepcionistaService = new RecepcionistaService();
    private String uriImg;
    private String codigo;
    
    public DialogModificarRecepcionista(java.awt.Frame parent, boolean modal, Recepcionista recepcionista) {
        super(parent, modal);
        initComponents();
        llenarDatosR(recepcionista);      
        this.codigo = recepcionista.getCodigo();
    }

    private void llenarDatosR(Recepcionista recepcionista) {        
        txtNumDocR.setText(recepcionista.getNumeroDocumento());        
        txtPriNombreR.setText(recepcionista.getPrimerNombre());
        txtSegNombreR.setText(recepcionista.getSegundoNombre());
        txtPriApellidoR.setText(recepcionista.getPrimerApellido());
        txtSegApellidoR.setText(recepcionista.getSegundoApellido());
        dcFechaNacimientoR.setDate(recepcionista.getFechaNacimiento());
        cbSexoR.setSelectedItem(recepcionista.getSexo());
        txtEmailR.setText(recepcionista.getEmail());
        txtCelularR.setText(recepcionista.getCelular());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarRecepcionista = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        lblImgUserR = new javax.swing.JLabel();
        cbSexoR = new javax.swing.JComboBox<>();
        dcFechaNacimientoR = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        cbEpsR = new javax.swing.JComboBox<>();
        txtEmailR = new jtextfieldround.JTextFieldRound();
        txtNumDocR = new jtextfieldround.JTextFieldRound();
        txtPriNombreR = new jtextfieldround.JTextFieldRound();
        txtSegNombreR = new jtextfieldround.JTextFieldRound();
        txtPriApellidoR = new jtextfieldround.JTextFieldRound();
        txtSegApellidoR = new jtextfieldround.JTextFieldRound();
        txtCelularR = new jtextfieldround.JTextFieldRound();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelAgregarRecepcionista.setBackground(new java.awt.Color(255, 255, 255));
        panelAgregarRecepcionista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(10, 92, 184));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GESTION RECEPCIONISTA");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, 442, 84));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estetoscopio.png"))); // NOI18N
        jPanel9.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 70, 70));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipo-medico.png"))); // NOI18N
        jPanel9.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 80, 60));

        jLabel59.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Tu salud es la nuestra");
        jPanel9.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 270, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dentista.png"))); // NOI18N
        jPanel9.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 80, 70));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visita-al-doctor.png"))); // NOI18N
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 80, 70));

        panelAgregarRecepcionista.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 130));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setText("CarjeSalud");
        panelAgregarRecepcionista.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Graphicloads-Medical-Health-Heart-beat.48.png"))); // NOI18N
        panelAgregarRecepcionista.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel71.setText("Sexo:");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 105, -1));

        jLabel73.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel73.setText("Celular:");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 220, -1));

        jLabel72.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel72.setText("Email:");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 220, -1));

        jLabel74.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel74.setText("Segundo Apellido:");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 220, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel30.setText("Primer Apellido:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 220, -1));

        jLabel75.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel75.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 220, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel22.setText("Primer Nombre:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 220, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel31.setText("Segundo Nombre:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 220, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel33.setText("Número de Documento:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 220, -1));

        jLabel76.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel76.setText("Eps:");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 130, 150, -1));

        lblImgUserR.setBackground(new java.awt.Color(232, 230, 229));
        lblImgUserR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgUserR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 255), null, null));
        jPanel1.add(lblImgUserR, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 160, 160));

        cbSexoR.setBackground(new java.awt.Color(0, 0, 0, 0));
        cbSexoR.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cbSexoR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(cbSexoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 60, 30));

        dcFechaNacimientoR.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel1.add(dcFechaNacimientoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 230, 30));

        jButton1.setBackground(new java.awt.Color(10, 92, 184));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Subir Foto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 160, 30));

        cbEpsR.setBackground(new java.awt.Color(0, 0, 0, 0));
        cbEpsR.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cbEpsR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coosalud", "Sanistas", "Comfamiliar", "Nueva Eps" }));
        jPanel1.add(cbEpsR, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 160, 150, 30));

        txtEmailR.setCaretColor(new java.awt.Color(0, 102, 153));
        txtEmailR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtEmailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 230, 30));

        txtNumDocR.setCaretColor(new java.awt.Color(0, 102, 153));
        txtNumDocR.setFocusable(false);
        txtNumDocR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNumDocR.setRequestFocusEnabled(false);
        jPanel1.add(txtNumDocR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, 30));

        txtPriNombreR.setCaretColor(new java.awt.Color(0, 102, 153));
        txtPriNombreR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtPriNombreR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 230, 30));

        txtSegNombreR.setCaretColor(new java.awt.Color(0, 102, 153));
        txtSegNombreR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtSegNombreR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 230, 30));

        txtPriApellidoR.setCaretColor(new java.awt.Color(0, 102, 153));
        txtPriApellidoR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtPriApellidoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 230, 30));

        txtSegApellidoR.setCaretColor(new java.awt.Color(0, 102, 153));
        txtSegApellidoR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtSegApellidoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 230, 30));

        txtCelularR.setCaretColor(new java.awt.Color(0, 102, 153));
        txtCelularR.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtCelularR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 230, 30));

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("ELIMINAR");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 150, 35));

        jButton9.setBackground(new java.awt.Color(10, 92, 184));
        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("GUARDAR");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 150, 35));

        panelAgregarRecepcionista.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 850, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelAgregarRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelAgregarRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        uriImg = escogerImagen(lblImgUserR, this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String numeroDocumento = txtNumDocR.getText();
        Recepcionista recepcionista = recepcionistaService.encontrarRecepcionista(numeroDocumento);
        int respuesta = JOptionPane.showConfirmDialog(this, "Confirmar eliminacion. \nRecepcionista : "
            + recepcionista.getPrimerNombre() + " " + recepcionista.getPrimerApellido());
        if (respuesta == JOptionPane.YES_OPTION) {
            recepcionistaService.eliminarRecepcionista(recepcionista);
            JOptionPane.showMessageDialog(this, "Recepcionista Eliminado");
            this.dispose();
        }    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Persona persona = new Recepcionista();
        Recepcionista recepcionista;
        if (!getDataForm(txtNumDocR, txtPriNombreR, txtSegNombreR, txtPriApellidoR, 
                txtSegApellidoR, txtEmailR, txtCelularR, dcFechaNacimientoR, 
                cbSexoR, cbEpsR, uriImg, persona)) {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos");
            return;
        }
        recepcionista = (Recepcionista) persona;
        recepcionista.setCodigo(codigo);
        if (recepcionistaService.encontrarRecepcionista(recepcionista.getNumeroDocumento()) == null) {
            JOptionPane.showMessageDialog(this, "Recepcionista no se encuentra registrado");
            return;
        }
        recepcionistaService.actualizarRecepcionista(recepcionista);
        limpiar(txtNumDocR, txtPriNombreR, txtSegNombreR, txtPriApellidoR, txtSegApellidoR, txtEmailR, txtCelularR);
        limpiar(dcFechaNacimientoR);
        JOptionPane.showMessageDialog(this, "Datos Actualizados con exito");
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModificarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModificarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModificarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModificarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModificarRecepcionista dialog = new DialogModificarRecepcionista(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEpsR;
    private javax.swing.JComboBox<String> cbSexoR;
    private com.toedter.calendar.JDateChooser dcFechaNacimientoR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblImgUserR;
    private javax.swing.JPanel panelAgregarRecepcionista;
    private jtextfieldround.JTextFieldRound txtCelularR;
    private jtextfieldround.JTextFieldRound txtEmailR;
    private jtextfieldround.JTextFieldRound txtNumDocR;
    private jtextfieldround.JTextFieldRound txtPriApellidoR;
    private jtextfieldround.JTextFieldRound txtPriNombreR;
    private jtextfieldround.JTextFieldRound txtSegApellidoR;
    private jtextfieldround.JTextFieldRound txtSegNombreR;
    // End of variables declaration//GEN-END:variables
}
