package vista;

import dominio.Doctor;
import dominio.Persona;
import java.awt.Color;
import javax.swing.JOptionPane;
import servicio.DoctorService;
import static util.FuncionesForm.*;

public class DialogModificarDoctor extends javax.swing.JDialog {

    private DoctorService doctorService = new DoctorService();
    private String uriImg;
    private String codigo;

    public DialogModificarDoctor(java.awt.Frame parent, boolean modal, Doctor doctor) {
        super(parent, modal);
        initComponents();
        llenarDatosD(doctor);
        this.codigo = doctor.getCodigo();
    }

    private void llenarDatosD(Doctor doctor) {
        txtNumDocD.setText(doctor.getNumeroDocumento());
        txtPriNombreD.setText(doctor.getPrimerNombre());
        txtSegNombreD.setText(doctor.getSegundoNombre());
        txtPriApellidoD.setText(doctor.getPrimerApellido());
        txtSegApellidoD.setText(doctor.getSegundoApellido());
        dcFechaNacimientoD.setDate(doctor.getFechaNacimiento());
        cbSexoD.setSelectedItem(doctor.getSexo());
        txtEmailD.setText(doctor.getEmail());
        cbEspecialidad.setSelectedItem(doctor.getEspecialidad());
        txtCelularD.setText(doctor.getCelular());
        lblImgUser.setIcon(cargarImagen(doctor, lblImgUser));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarDoctor = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblImgUser = new javax.swing.JLabel();
        dcFechaNacimientoD = new com.toedter.calendar.JDateChooser();
        cbSexoD = new javax.swing.JComboBox<>();
        cbEpsD = new javax.swing.JComboBox<>();
        cbEspecialidad = new javax.swing.JComboBox<>();
        txtCelularD = new jtextfieldround.JTextFieldRound();
        txtNumDocD = new jtextfieldround.JTextFieldRound();
        txtPriNombreD = new jtextfieldround.JTextFieldRound();
        txtSegNombreD = new jtextfieldround.JTextFieldRound();
        txtPriApellidoD = new jtextfieldround.JTextFieldRound();
        txtSegApellidoD = new jtextfieldround.JTextFieldRound();
        txtEmailD = new jtextfieldround.JTextFieldRound();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelAgregarDoctor.setBackground(new java.awt.Color(255, 255, 255));
        panelAgregarDoctor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(10, 92, 184));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 46)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GESTION DOCTOR");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, 442, 84));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estetoscopio.png"))); // NOI18N
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 70, 70));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipo-medico.png"))); // NOI18N
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 80, 60));

        jLabel55.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Tu salud es la nuestra");
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 270, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dentista.png"))); // NOI18N
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 80, 70));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visita-al-doctor.png"))); // NOI18N
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 80, 70));

        panelAgregarDoctor.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 860, 130));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setText("CarjeSalud");
        panelAgregarDoctor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 240, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Graphicloads-Medical-Health-Heart-beat.48.png"))); // NOI18N
        panelAgregarDoctor.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel66.setText("Sexo:");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 105, -1));

        jLabel67.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel67.setText("Email:");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 220, -1));

        jLabel68.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel68.setText("Celular:");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 220, -1));

        jLabel64.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel64.setText("Segundo Apellido:");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 220, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel28.setText("Primer Apellido:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, -1));

        jLabel65.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel65.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 220, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Primer Nombre:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 220, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel29.setText("Segundo Nombre:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setText("Número de Documento:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 220, -1));

        jLabel69.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel69.setText("Especialidad:");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 220, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Eps:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 140, 50, -1));

        lblImgUser.setBackground(new java.awt.Color(232, 230, 229));
        lblImgUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, null, null));
        jPanel1.add(lblImgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 160, 160));

        dcFechaNacimientoD.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel1.add(dcFechaNacimientoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 220, 30));

        cbSexoD.setBackground(new java.awt.Color(0, 0, 0, 0));
        cbSexoD.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cbSexoD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(cbSexoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 70, 25));

        cbEpsD.setBackground(new java.awt.Color(0, 0, 0, 0));
        cbEpsD.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cbEpsD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coosalud", "Sanitas", "Nueva Eps" }));
        jPanel1.add(cbEpsD, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 130, 25));

        cbEspecialidad.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        cbEspecialidad.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina General", "Psicologia", "Pediatria", "Ortopedia" }));
        jPanel1.add(cbEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 220, 30));

        txtCelularD.setCaretColor(new java.awt.Color(0, 102, 153));
        txtCelularD.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jPanel1.add(txtCelularD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 220, 30));

        txtNumDocD.setCaretColor(new java.awt.Color(0, 102, 153));
        txtNumDocD.setFocusable(false);
        txtNumDocD.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        txtNumDocD.setRequestFocusEnabled(false);
        jPanel1.add(txtNumDocD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 220, 30));

        txtPriNombreD.setCaretColor(new java.awt.Color(0, 102, 153));
        txtPriNombreD.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jPanel1.add(txtPriNombreD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 220, 30));

        txtSegNombreD.setCaretColor(new java.awt.Color(0, 102, 153));
        txtSegNombreD.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jPanel1.add(txtSegNombreD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 220, 30));

        txtPriApellidoD.setCaretColor(new java.awt.Color(0, 102, 153));
        txtPriApellidoD.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jPanel1.add(txtPriApellidoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 220, 30));

        txtSegApellidoD.setCaretColor(new java.awt.Color(0, 102, 153));
        txtSegApellidoD.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jPanel1.add(txtSegApellidoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 220, 30));

        txtEmailD.setCaretColor(new java.awt.Color(0, 102, 153));
        txtEmailD.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jPanel1.add(txtEmailD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 220, 30));

        jButton2.setBackground(new java.awt.Color(10, 92, 184));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Subir Foto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 160, 30));

        jButton7.setBackground(new java.awt.Color(10, 92, 184));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("GUARDAR");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 120, 35));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ELIMINAR");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 120, 35));

        panelAgregarDoctor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 860, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAgregarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAgregarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        uriImg = escogerImagen(lblImgUser, this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Persona persona = new Doctor();
        Doctor doctor;
        if (!getDataForm(txtNumDocD, txtPriNombreD, txtSegNombreD, txtPriApellidoD, 
                txtSegApellidoD, txtEmailD, txtCelularD, dcFechaNacimientoD, cbSexoD,
                cbEpsD, uriImg, persona)) {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos");
            return;
        }
        doctor = (Doctor) persona;
        String especialidad = cbEspecialidad.getSelectedItem().toString();
        doctor.setCodigo(codigo);
        doctor.setEspecialidad(especialidad);
        if (doctorService.encontrarDoctor(doctor.getNumeroDocumento()) == null) {
            JOptionPane.showMessageDialog(this, "Doctor no se encuentra registrado");
            return;
        }

        doctorService.actualizarDoctor(doctor);
        limpiar( txtNumDocD, txtPriNombreD, txtSegNombreD, txtPriApellidoD, txtSegApellidoD, txtEmailD, txtCelularD);
        limpiar(dcFechaNacimientoD);
        JOptionPane.showMessageDialog(this, "Datos Actualizados con exito");
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numeroDocumento = txtNumDocD.getText();
        Doctor doctor = doctorService.encontrarDoctor(numeroDocumento);
        int respuesta = JOptionPane.showConfirmDialog(this, "Confirmar eliminacion. \nDoctor : "
                + doctor.getPrimerNombre() + " " + doctor.getPrimerApellido());
        if (respuesta == JOptionPane.YES_OPTION) {
            doctorService.eliminarDoctor(doctor);
            JOptionPane.showMessageDialog(this, "Doctor Eliminado");
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModificarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModificarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModificarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModificarDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModificarDoctor dialog = new DialogModificarDoctor(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEpsD;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbSexoD;
    private com.toedter.calendar.JDateChooser dcFechaNacimientoD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblImgUser;
    private javax.swing.JPanel panelAgregarDoctor;
    private jtextfieldround.JTextFieldRound txtCelularD;
    private jtextfieldround.JTextFieldRound txtEmailD;
    private jtextfieldround.JTextFieldRound txtNumDocD;
    private jtextfieldround.JTextFieldRound txtPriApellidoD;
    private jtextfieldround.JTextFieldRound txtPriNombreD;
    private jtextfieldround.JTextFieldRound txtSegApellidoD;
    private jtextfieldround.JTextFieldRound txtSegNombreD;
    // End of variables declaration//GEN-END:variables
}
