package vista;

import dominio.*;
import java.awt.Color;
import static java.lang.System.exit;
import javax.swing.JOptionPane;
import servicio.DoctorService;
import servicio.RecepcionistaService;
import sombra.TextPrompt;

public class VentanaPrincipal extends javax.swing.JFrame {

    private DoctorService doctorService = new DoctorService();
    private RecepcionistaService recepcionistaService = new RecepcionistaService();
    
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        TextPrompt prueba = new TextPrompt("Usuario", txtusuario);
        TextPrompt codigo = new TextPrompt("Contraseña", txtcontra);
        txtusuario.setText("1008829");
        txtcontra.setText("10001");
        cbbCargo.setSelectedIndex(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtcontra = new javax.swing.JPasswordField();
        cbbCargo = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelAcciones = new javax.swing.JPanel();
        panelMini = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Contraseña*");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("INICIAR SESION");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Usuario*");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, -1));

        txtusuario.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtusuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtusuario.setBorder(null);
        jPanel9.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 370, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel9.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 370, 20));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel9.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 370, 20));

        txtcontra.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtcontra.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtcontra.setBorder(null);
        jPanel9.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 370, 30));

        cbbCargo.setBackground(new java.awt.Color(0, 0, 0, 0));
        cbbCargo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cbbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar cargo>", "Administrador", "Doctor", "Recepcionista" }));
        cbbCargo.setBorder(null);
        jPanel9.add(cbbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 370, 40));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel9.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 370, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Graphicloads-Medical-Health-Heart-beat.48.png"))); // NOI18N
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 50));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENTRAR");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 150, 40));

        panelAcciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMini.setBackground(new java.awt.Color(255, 255, 255));
        panelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMiniMouseExited(evt);
            }
        });
        panelMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/min.png"))); // NOI18N
        panelMini.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelAcciones.add(panelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelExit.setBackground(new java.awt.Color(255, 255, 255));
        panelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelExitMouseExited(evt);
            }
        });
        panelExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setToolTipText("");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        panelExit.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelAcciones.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jPanel9.add(panelAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 100, 50));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 490, 570));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUESTRA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TU SALUD ES LA ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a - Login hospital.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 570));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cargo = cbbCargo.getSelectedItem().toString();
        if (txtusuario.getText().isBlank() || txtcontra.getPassword().length < 1) {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos");
            return;
        }
        String adminUser = "12345";
        String adminPass = "12345";
        String numeroDocumento = txtusuario.getText();
        char[] contraseña = txtcontra.getPassword();
        String sContraseña = "";
        String contraseña1 = new String(txtcontra.getPassword());
        for (int i = 0; i < contraseña.length; i++) {
            sContraseña += String.valueOf(contraseña[i]);
        }
        switch (cargo) {
            case "Administrador" -> {
                if (adminUser.equals(numeroDocumento) && contraseña1.equals(adminPass)) {
                    new VentanaAdministrador().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario no tiene cuanta asignada");
                }
            }
            case "Doctor" -> {
                Doctor doctor = doctorService.encontrarDoctor(numeroDocumento);
                if (doctor == null) {
                    JOptionPane.showMessageDialog(this, "El usuario no tiene cuanta asignada");
                    return;
                }
                if (sContraseña.equals(doctor.getCodigo())) {
                    new VentanaDoctor(doctor).setVisible(true);
                    this.dispose();
                }
            }
            case "Recepcionista" -> {
                Recepcionista recepcionista = recepcionistaService.encontrarRecepcionista(numeroDocumento);
                if (recepcionista == null) {
                    JOptionPane.showMessageDialog(this, "El usuario no tiene cuanta asignada");
                    return;
                }
                if (sContraseña.equals(recepcionista.getCodigo())) {
                    new VentanaRecepcionista(recepcionista).setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseEntered
        panelExit.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_panelExitMouseEntered

    private void panelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseExited
        panelExit.setBackground(Color.white);
    }//GEN-LAST:event_panelExitMouseExited

    private void panelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseClicked
        exit(0);
    }//GEN-LAST:event_panelExitMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        panelExitMouseClicked(null);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        panelExitMouseEntered(null);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        panelExitMouseExited(null);
    }//GEN-LAST:event_jLabel8MouseExited

    private void panelMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiniMouseEntered
        panelMini.setBackground(Color.GRAY);
    }//GEN-LAST:event_panelMiniMouseEntered

    private void panelMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiniMouseExited
        panelMini.setBackground(Color.white);
    }//GEN-LAST:event_panelMiniMouseExited

    private void panelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiniMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMiniMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbCargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelExit;
    private javax.swing.JPanel panelMini;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
