package vista;

import dominio.*;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import static java.lang.System.exit;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import servicio.*;
import static util.FuncionesForm.*;
import static util.FuncionesPersona.obtenerEdad;
import util.FuncionesVista;
import util.Reportes;

public class VentanaDoctor extends javax.swing.JFrame {

    private CitaService citaService = new CitaService();
    private HistoriaService clinicaService = new HistoriaService();
//    private PacienteService pacienteService = new PacienteService();
    private Cita cita;
    private Doctor doctor;

    FuncionesVista fv = new FuncionesVista();

    public VentanaDoctor(Doctor doctor) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.doctor = doctor;
        mostrarPacientesEnTabla(doctor);
//        lblImgPerfil.setIcon(cargarImagen(doctor, lblImgPerfil));
        lblNombreDoctor.setText(doctor.getFullName());
        lblMostrarFecha.setText(formatearFecha(new Date()));
    }

    private final DefaultListModel<String> listModel = new DefaultListModel<>();
    Map<String, String[]> mapMedicamentos = new HashMap();
    int c = 0;

    private void mostrarPacientesEnTabla(Doctor doctor) {
        DefaultTableModel modelo = (DefaultTableModel) tbPacientesCita.getModel();
        List<Cita> citas = citaService.listarCitasDoctor(doctor);

        modelo.setRowCount(0);

        String fechaActual = formatearFecha(new Date());
        for (Cita cita1 : citas) {
            String fechaCita = formatearFecha(cita1.getFecha());
            if (fechaCita.equals(fechaActual)) {
                Object[] fila = {
                    cita1.getIdCita(),
                    cita1.getHora(),
                    cita1.getPaciente().getNumeroDocumento(),
                    cita1.getPaciente().getPrimerNombre(),
                    cita1.getPaciente().getPrimerApellido(),
                    cita1.getPaciente().getEps(),};
                modelo.addRow(fila);
            }
        }
        tbPacientesCita.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImgPerfil = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblNombreDoctor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPacientesCita = new rojerusan.RSTableMetro();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaDiagnostico1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        txtCedula = new jtextfieldround.JTextFieldRound();
        txtNombres = new jtextfieldround.JTextFieldRound();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblHemogoblina = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblGlucosa = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblPlaquetas = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblColesterol = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkObesidad = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFechaHora = new jtextfieldround.JTextFieldRound();
        txtTemperatura = new jtextfieldround.JTextFieldRound();
        txtCedula2 = new jtextfieldround.JTextFieldRound();
        txtApellido = new jtextfieldround.JTextFieldRound();
        txtSexo = new jtextfieldround.JTextFieldRound();
        txtEdad = new jtextfieldround.JTextFieldRound();
        txtPeso = new jtextfieldround.JTextFieldRound();
        txtEstatura = new jtextfieldround.JTextFieldRound();
        txtDisasolica = new jtextfieldround.JTextFieldRound();
        txtSistolica = new jtextfieldround.JTextFieldRound();
        txtFrCardiaca = new jtextfieldround.JTextFieldRound();
        txtNombre = new jtextfieldround.JTextFieldRound();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDiagnostico = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jsCantidadMedicamento = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        btnAddMedicamento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMedicamentos = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        txtMedicamento = new jtextfieldround.JTextFieldRound();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelAcciones = new javax.swing.JPanel();
        panelMini = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblMostrarFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 92, 184));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgPerfil.setBackground(new java.awt.Color(255, 255, 255));
        lblImgPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        jPanel2.add(lblImgPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 190));

        jPanel3.setBackground(new java.awt.Color(10, 92, 184));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Diagnosticos, revision detal ...");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 420, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visita-al-doctor.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 80, 70));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dentista.png"))); // NOI18N
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 80, 70));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estetoscopio.png"))); // NOI18N
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 70, 70));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipo-medico.png"))); // NOI18N
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 80, 60));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Tu salud es la nuestra");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 270, -1));

        lblNombreDoctor.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblNombreDoctor.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreDoctor.setText("Doctor");
        jPanel3.add(lblNombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 230, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 990, 130));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Cita medica");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 40));

        tbPacientesCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod. Cita", "Hora", "Numero Documento", "Nombres", "Apellidos", "Eps"
            }
        ));
        tbPacientesCita.setAltoHead(25);
        tbPacientesCita.setColorBackgoundHead(new java.awt.Color(0, 51, 102));
        tbPacientesCita.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        tbPacientesCita.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tbPacientesCita.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tbPacientesCita.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbPacientesCita.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbPacientesCita.setGrosorBordeFilas(0);
        tbPacientesCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPacientesCitaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbPacientesCita);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 700, 330));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reload32.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 60, 32, 32));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jLabel8.setText("Numero Documento");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jLabel9.setText("Nombres");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 140, -1));

        areaDiagnostico1.setColumns(20);
        areaDiagnostico1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaDiagnostico1.setLineWrap(true);
        areaDiagnostico1.setRows(5);
        areaDiagnostico1.setRequestFocusEnabled(false);
        jScrollPane5.setViewportView(areaDiagnostico1);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, 150));

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ATENDER");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 130, 35));

        txtCedula.setRequestFocusEnabled(false);
        jPanel10.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 180, -1));

        txtNombres.setRequestFocusEnabled(false);
        jPanel10.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 180, -1));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 380, 330));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print_1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 60, 32, 32));

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Cedula");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 20));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Nombre");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 20));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setText("Apelllido");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 20));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setText("Fecha - Hora");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, 20));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Estado");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel25.setText("Tension Arterial");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Sexo :");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, 25));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Disasolica :");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, 25));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel28.setText("Hemoglobina :");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, 25));

        lblHemogoblina.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel5.add(lblHemogoblina, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 70, 25));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel29.setText("Glucosa :");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, 25));

        lblGlucosa.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel5.add(lblGlucosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 70, 25));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel30.setText("Plaquetas :");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, 25));

        lblPlaquetas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel5.add(lblPlaquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 70, 25));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel31.setText("Colesterol :");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, 25));

        lblColesterol.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel5.add(lblColesterol, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 70, 25));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel32.setText("Obesidad");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, 25));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Sistolica  :");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 25));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Edad :");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 60, 25));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Peso :");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 60, 25));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Fr cardiaca :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, 25));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Estatura :");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 80, 25));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Temperatura :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, 25));

        checkObesidad.setEnabled(false);
        jPanel5.add(checkObesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, 25));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIGUIENTE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diagnostico.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 150, 140));

        txtFechaHora.setFocusable(false);
        txtFechaHora.setRequestFocusEnabled(false);
        jPanel5.add(txtFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 190, -1));
        jPanel5.add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 60, -1));

        txtCedula2.setFocusable(false);
        txtCedula2.setRequestFocusEnabled(false);
        jPanel5.add(txtCedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        txtApellido.setFocusable(false);
        txtApellido.setRequestFocusEnabled(false);
        jPanel5.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 130, -1));

        txtSexo.setFocusable(false);
        txtSexo.setRequestFocusEnabled(false);
        jPanel5.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 60, -1));

        txtEdad.setFocusable(false);
        txtEdad.setRequestFocusEnabled(false);
        jPanel5.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, -1));
        jPanel5.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 60, -1));
        jPanel5.add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 60, -1));
        jPanel5.add(txtDisasolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 60, -1));
        jPanel5.add(txtSistolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, -1));
        jPanel5.add(txtFrCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 60, -1));

        txtNombre.setFocusable(false);
        txtNombre.setRequestFocusEnabled(false);
        jPanel5.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 130, -1));

        jTabbedPane1.addTab("tab2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel20.setText("Diagnostico");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        areaDiagnostico.setColumns(20);
        areaDiagnostico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaDiagnostico.setLineWrap(true);
        areaDiagnostico.setRows(5);
        areaDiagnostico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(areaDiagnostico);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 320, 280));

        btnFinalizar.setBackground(new java.awt.Color(51, 51, 255));
        btnFinalizar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel6.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 110, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel34.setText("Medicamentos");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel33.setText("Cant...");

        jsCantidadMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel35.setText("Nombre");

        btnAddMedicamento.setBackground(new java.awt.Color(51, 51, 255));
        btnAddMedicamento.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAddMedicamento.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMedicamento.setText("AGREGAR");
        btnAddMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicamentoActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medicamento.png"))); // NOI18N

        jScrollPane1.setViewportView(listaMedicamentos);

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ELIMINAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jsCantidadMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel34)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 47, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnAddMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel35)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jsCantidadMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddMedicamento))
                            .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 370, 330));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("HISTORIA CLINICA");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("EXAMENES");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 140, 40));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 320, 40));

        jTabbedPane1.addTab("tab3", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1150, 550));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Graphicloads-Medical-Health-Heart-beat.48.png"))); // NOI18N
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 60, 60));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel7.setText("CarjeSalud");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 250, -1));

        panelAcciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMini.setBackground(new java.awt.Color(255, 255, 255));
        panelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMiniMouseExited(evt);
            }
        });
        panelMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/min.png"))); // NOI18N
        panelMini.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelAcciones.add(panelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelExit.setBackground(new java.awt.Color(255, 255, 255));
        panelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelExitMouseExited(evt);
            }
        });
        panelExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");
        jLabel14.setToolTipText("");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        panelExit.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelAcciones.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jPanel1.add(panelAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 100, 50));

        lblMostrarFecha.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblMostrarFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrarFecha.setText("04/02/2024  - 14:30");
        jPanel1.add(lblMostrarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicamentoActionPerformed
        if (listModel.getSize() >= 5) {
            JOptionPane.showMessageDialog(this, "Solo se puede recetar un maximo\nde 5 medicamentos");
            return;
        }
        String posologia = JOptionPane.showInputDialog("Posologia");
        int cantidad = Integer.parseInt(jsCantidadMedicamento.getValue().toString());
        String sCantidad = jsCantidadMedicamento.getValue().toString();
        String medicamento = txtMedicamento.getText();
        if (cantidad < 1 || medicamento.isBlank() || posologia.isBlank() || isNumeric(posologia) || isNumeric(medicamento)) {
            JOptionPane.showMessageDialog(this, "Error al agregar medicamento\nIntente nuevamente");
            txtMedicamento.setText("");
            jsCantidadMedicamento.setValue(1);
            return;
        }
        String[] value = {sCantidad, medicamento, posologia};
        c++;
        String key = c + "";
        mapMedicamentos.put(key, value);
        String datos = cantidad + " - " + medicamento + " - " + posologia;
        listModel.addElement(datos);
        listaMedicamentos.setModel(listModel);
        txtMedicamento.setText("");
        jsCantidadMedicamento.setValue(1);
    }//GEN-LAST:event_btnAddMedicamentoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        String message = "¿Desea finalizar la consulta?";
        String path = "/imagenes/question.png";
        int r = JOptionPane.showConfirmDialog(this, message, "Finalizar consulta", 0, 0, fv.crearIcono(path));
        String diagnostico, datosCita, medicamentos, estadoPaciente;
        if (r == JOptionPane.YES_OPTION) {
            Paciente paciente = cita.getPaciente();
            medicamentos = extraerMedicamentos();
            datosCita = extraerDatosCita(cita);
            estadoPaciente = extraerEstadoPaciente();
            diagnostico = areaDiagnostico.getText();
            Historia historiaClinica = new Historia(paciente, new Date(), medicamentos, estadoPaciente, diagnostico, datosCita);
            clinicaService.guardarHistoriaClinica(historiaClinica);
            citaService.eliminarCita(cita);
            JOptionPane.showMessageDialog(this, "Consulta Finalizada");
            limpiarCampos();
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (checkField(txtTemperatura) || checkField(txtPeso) || checkField(txtFrCardiaca)
                || checkField(txtEstatura) || checkField(txtDisasolica) || checkField(txtSistolica)) {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos");
            return;
        }
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int fila = tbPacientesCita.getSelectedRow();
        if (fila == -1 || txtCedula.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Escoja un paciente");
            return;
        }
        txtCedula2.setText(cita.getPaciente().getNumeroDocumento());
        txtNombre.setText(cita.getPaciente().getPrimerNombre());
        txtApellido.setText(cita.getPaciente().getPrimerApellido());
        txtFechaHora.setText(formatearFecha(cita.getFecha()) + " / " + cita.getHora());
        txtSexo.setText(cita.getPaciente().getSexo());
        txtEdad.setText(obtenerEdad(cita.getPaciente()));
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tbPacientesCita.getSelectedRow() != -1 || tbPacientesCita.getSelectedRows().length >= 1) {
            tbPacientesCita.clearSelection();
            mostrarPacientesEnTabla(doctor);
            limpiar(txtNombres, txtCedula);
            limpiar(areaDiagnostico1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbPacientesCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPacientesCitaMouseClicked
        int fila = tbPacientesCita.getSelectedRow();
        Integer codigo = (Integer) tbPacientesCita.getValueAt(fila, 0);
        cita = citaService.encontrarCita(codigo);

        txtNombres.setText(cita.getPaciente().getFullName());
        txtCedula.setText(cita.getPaciente().getNumeroDocumento());
        areaDiagnostico1.setText(cita.getMotivo());
        tbPacientesCita.setFocusable(false);
    }//GEN-LAST:event_tbPacientesCitaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int i = listaMedicamentos.getSelectedIndex();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione uno o mas medicamentos");
            return;
        }
        listModel.remove(i);
        listaMedicamentos.setModel(listModel);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void panelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiniMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMiniMouseClicked

    private void panelMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiniMouseEntered
        panelMini.setBackground(Color.GRAY);
    }//GEN-LAST:event_panelMiniMouseEntered

    private void panelMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMiniMouseExited
        panelMini.setBackground(Color.white);
    }//GEN-LAST:event_panelMiniMouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        panelExitMouseClicked(null);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        panelExitMouseEntered(null);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        panelExitMouseExited(null);
    }//GEN-LAST:event_jLabel14MouseExited

    private void panelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseClicked
        exit(0);
    }//GEN-LAST:event_panelExitMouseClicked

    private void panelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseEntered
        panelExit.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_panelExitMouseEntered

    private void panelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseExited
        panelExit.setBackground(Color.white);
    }//GEN-LAST:event_panelExitMouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (tbPacientesCita.getRowCount() >= 1) {
            Reportes.exportarExcel(tbPacientesCita);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogVerHistoria dvh = new DialogVerHistoria(this, true, cita.getPaciente());
        dvh.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void limpiarCampos() {
        limpiar(txtNombres, txtCedula, txtCedula2, txtNombre, txtApellido,
                txtFechaHora, txtSexo, txtEdad, txtDisasolica, txtSistolica,
                txtFrCardiaca, txtTemperatura, txtEstatura, txtPeso);
        limpiar(areaDiagnostico, areaDiagnostico1);
        jButton3ActionPerformed(null);
    }

    private static void abrirPDFConDesktop(String filePath) {
        try {
            File file = new File(filePath);
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(file);
            } else {
                System.out.println("La apertura automática no es compatible en este sistema.");
            }
        } catch (Exception e) {
            System.err.println("Error al abrir archivo : \n" + e.getMessage());
        }
    }

    private String extraerMedicamentos() {
        JSONArray medi = new JSONArray();
        Set<String> keys = mapMedicamentos.keySet();
        for (String key : keys) {
            String[] m = mapMedicamentos.get(key);
            medi.put(new JSONObject()
                    .put("cantidad", m[0])
                    .put("medicamento", m[1])
                    .put("posologia", m[2]));
        }
        return medi.toString();
    }

    private String extraerDatosCita(Cita cita) {
        JSONObject datos = new JSONObject()
                .put("doctor", cita.getDoctor().getNumeroDocumento())
                .put("fecha", formatearFecha(cita.getFecha()) + "/" + cita.getHora())
                .put("tipo", cita.getTipo())
                .put("motivo", cita.getMotivo());
        return datos.toString();
    }

    private String extraerEstadoPaciente() {
        String edad, peso, estatura, disasolica, sistolica, pulso, temperatura;
        edad = txtEdad.getText();
        peso = txtPeso.getText();
        estatura = txtEstatura.getText();
        disasolica = txtDisasolica.getText();
        sistolica = txtSistolica.getText();
        pulso = txtFrCardiaca.getText();
        temperatura = txtTemperatura.getText();
        JSONObject datos = new JSONObject()
                .put("edad", edad)
                .put("peso", peso)
                .put("estatura", estatura)
                .put("disasolica", disasolica)
                .put("sistolica", sistolica)
                .put("temperatura", temperatura)
                .put("pulso", pulso);
        return datos.toString();
    }

//    private List<SaleDetails> recoveryProducts(Sale sale) {
//        JSONArray products = new JSONArray(sale.getProducts());
//        List<SaleDetails> salesDetails = new ArrayList<>();
//        for (int i = 0; i < products.length(); i++) {
//            JSONObject product = products.getJSONObject(i);
//            var name = product.getString("name");
//            var p = productService.findProductByName(name);
//            var amount = product.getInt("amount");
//            var saleDetails = new SaleDetails(p, amount);
//            salesDetails.add(saleDetails);
//        }
//        for (SaleDetails saleDetails1 : salesDetails) {
//            logger.info(saleDetails1.toString());
//        }
//        logger.info("product json => " + products);
//        return salesDetails;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDoctor(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDiagnostico;
    private javax.swing.JTextArea areaDiagnostico1;
    private javax.swing.JButton btnAddMedicamento;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JCheckBox checkObesidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner jsCantidadMedicamento;
    private javax.swing.JLabel lblColesterol;
    private javax.swing.JLabel lblGlucosa;
    private javax.swing.JLabel lblHemogoblina;
    private javax.swing.JLabel lblImgPerfil;
    private javax.swing.JLabel lblMostrarFecha;
    private javax.swing.JLabel lblNombreDoctor;
    private javax.swing.JLabel lblPlaquetas;
    private javax.swing.JList<String> listaMedicamentos;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelExit;
    private javax.swing.JPanel panelMini;
    private rojerusan.RSTableMetro tbPacientesCita;
    private jtextfieldround.JTextFieldRound txtApellido;
    private jtextfieldround.JTextFieldRound txtCedula;
    private jtextfieldround.JTextFieldRound txtCedula2;
    private jtextfieldround.JTextFieldRound txtDisasolica;
    private jtextfieldround.JTextFieldRound txtEdad;
    private jtextfieldround.JTextFieldRound txtEstatura;
    private jtextfieldround.JTextFieldRound txtFechaHora;
    private jtextfieldround.JTextFieldRound txtFrCardiaca;
    private jtextfieldround.JTextFieldRound txtMedicamento;
    private jtextfieldround.JTextFieldRound txtNombre;
    private jtextfieldround.JTextFieldRound txtNombres;
    private jtextfieldround.JTextFieldRound txtPeso;
    private jtextfieldround.JTextFieldRound txtSexo;
    private jtextfieldround.JTextFieldRound txtSistolica;
    private jtextfieldround.JTextFieldRound txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
